### PR TITLE
Laravel 8.x Compatibility

### PR DESCRIPTION
**Pull request by nivv**

### CODE REVIEW

**Comment by nivv** [comment]
related to issue #117

**Comment by mojtabaahn** [comment]
@Omranic & @ppalmeida Please merge this pull ASAP

**Comment by jnbn** [comment]
@Omranic can you please have a look at this PR please?

**Comment by Omranic** [comment]
Hello, thank you for your patience, this is now done! Check latest release!!

This package now supports Laravel v8, PHP v8, Composer v2, enjoy 🥳

CC @nivv @jnbn @mojtabaahn

**Pull request closed without merging**
