### PR TITLE
Adjustments to work with Laravel Cashier

### PR DESCRIPTION
**Pull request by insign**
Adapting to avoid conflicts with Laravel Cashier without causing breaking changes.

### CODE REVIEW

**Comment by Omranic** [comment]
Would you kindly check [contribution guides](https://github.com/rinvex/laravel-categories/blob/master/CONTRIBUTING.md) for future PRs as we're following git-flow model, and all PRs should be submitted to `develop` branch.

**Comment by insign** [comment]
Sorry about that. This PR still valid?

**Comment by rennokki** [comment]
I honestly think that adding a new trait to this package like `HasSubscriptionsWithCashier` that does exactly what this does: https://github.com/rinvex/laravel-subscriptions/pull/74/files#diff-04c6e90faac2675aa89e2176d2eec7d8R309 would be much better because it would fix the issues on compatibility.

Also, using `rinvex` in function names does not describe well anything. `planSubscription`-kind of names would be much better.

**Comment by Omranic** [comment]
Thank you for your contribution, and your passion. In my opinion, both [Rinvex Subscriptions](https://github.com/rinvex/laravel-subscriptions) & [Laravel Cashier](https://laravel.com/docs/master/billing) should NOT be used together, as I believe both are alternative solutions, tackling the same subscriptions feature, in two different ways.

I'd rather add **incompatibility disclaimer** in the docs, rather than renaming the internal methods to allow both packages to work side-by-side. Personally I don't know how can both packages used together at the same time, if you've a specific scenario or use case to explain this, please mention here so we can adapt and make this package better.

**Comment by insign** [comment]
The only problem I see I to share the same methods names. For me, I`ll need to find a fix...

**Comment by insign** [comment]
Cashier doesn't control usage locally, and remotely it charges per use.

**Comment by insign** [comment]
Here how I fixed:

```php
<?php


namespace App\Traits;

use Carbon\Carbon;
use Laravel\Cashier\Billable;
use Rinvex\Subscriptions\Models\Plan;
use Rinvex\Subscriptions\Models\PlanSubscription;
use Rinvex\Subscriptions\Traits\HasSubscriptions;

trait Subscriptions
{
   use HasSubscriptions, Billable {
      HasSubscriptions::newSubscription as rinvex__newSubscription;
      HasSubscriptions::subscription as rinvex__subscription;
      HasSubscriptions::subscription as rinvex__subscription;

      Billable::subscription as cashier__subscription;
      Billable::subscriptions as cashier__subscriptions;
      Billable::newSubscription as cashier__newSubscription;
   }

   public function logicError()
   : void
   {
      throw new \LogicException('You have to specify cashier or rinvex');
   }

   public function subscription()
   : void
   {
      $this->logicError();
   }

   public function subscriptions()
   : void
   {
      $this->logicError();
   }

   public function newSubscription()
   : void
   {
      $this->logicError();
   }

   public function rinvexNewSubscription($subscription, Plan $plan, Carbon $startDate = null): PlanSubscription
   {
      return $this->rinvex__newSubscription($subscription, $plan, $startDate);
   }

}
```

**Comment by Omranic** [comment]
Thank you for your patience, this is now fixed in https://github.com/rinvex/laravel-subscriptions/commit/3eedf73b8a685f9f6096ad7e30bf5a1c4256fbd9

**Pull request closed without merging**
